name: Android CI

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Access kakao key
      env:
        KAKAO_KEY_MANIFEST: ${{ secrets.KAKAO_KEY_MANIFEST }}
      run: echo kakao_key_manifest=\"$KAKAO_KEY_MANIFEST\" >> ./local.properties

    - name: Access kakao native key
      env:
        KAKAO_NATIVE_KEY: ${{ secrets.KAKAO_NATIVE_KEY }}
      run: echo kakao_native_key=\"$KAKAO_NATIVE_KEY\" >> ./local.properties
    
    - name: Access naver client id
      env:
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
      run: echo naver_api_client_id=\"$NAVER_CLIENT_ID\" >> ./local.properties
    
    - name: Access naver client secret
      env:
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
      run: echo naver_api_client_secret=\"$NAVER_CLIENT_SECRET\" >> ./local.properties
    
    - name: Access naver app name
      env:
        NAVER_APP_NAME: ${{ secrets.NAVER_APP_NAME }}
      run: echo naver_api_app_name=\"$NAVER_APP_NAME\" >> ./local.properties

    - name: Access spoon feed server api base url
      env:
        NAVER_APP_NAME: ${{ secrets.SPOONFEED_SERVER_API_BASE_URL }}
      run: echo spoonfeed_server_api_base_url=\"SPOONFEED_SERVER_API_BASE_URL\" >> ./local.properties

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
